from PATH import *
import os
print(ANNOTATION_PATH)
# python {'C:\NOIRECODE\PYTHON\PROJECTSB\HANDSIGNS\TENSORFLOW\SCRIPTS\\generate_tfrecord.py'}
# - x {'C:\NOIRECODE\PYTHON\PROJECTSB\HANDSIGNS\TENSORFLOW\WORKSPACE\IMAGES\train'}
# - l {'C:\NOIRECODE\PYTHON\PROJECTSB\HANDSIGNS\TENSORFLOW\WORKSPACE\ANNOTATIONS\label_map.pbtxt'}
# - o {'C:\NOIRECODE\PYTHON\PROJECTSB\HANDSIGNS\TENSORFLOW\WORKSPACE\ANNOTATIONS\train.record'}
os.system('cmd /k "py C:\\NOIRECODE\\PYTHON\\PROJECTSB\\HANDSIGNS\\TENSORFLOW\\SCRIPTS\\generate_tfrecord.py - x C:\\NOIRECODE\\PYTHON\\PROJECTSB\\HANDSIGNS\\TENSORFLOW\\WORKSPACE\\IMAGES\\train - l C:\\NOIRECODE\\PYTHON\\PROJECTSB\\HANDSIGNS\\TENSORFLOW\\WORKSPACE\\ANNOTATIONS\\label_map.pbtxt - o C:\\NOIRECODE\\PYTHON\\PROJECTSB\\HANDSIGNS\\TENSORFLOW\\WORKSPACE\\ANNOTATIONS\\train.record"')
